[pytest]
DJANGO_SETTINGS_MODULE = test_settings
addopts = --nomigrations --cov=group_selection_plugin --cov-report=html group_selection_plugin

[run]
omit =
    *apps.py,
    *migrations/*.py,
    *settings*.py,
    *tests/*.py,
    *urls.py,
    manage.py,
    setup.py,
