[tox]
envlist = py{311,312}-django{42}

[testenv]
deps =
    django42: Django>=4.2,<4.3
    -r{toxinidir}/requirements/dev.txt
commands =
    pytest {posargs:group_selection_plugin/tests --cov group_selection_plugin}
