# Generated by Django 5.2.12 on 2026-04-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_selection_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnerselection',
            options={'ordering': ['-modified']},
        ),
    ]
